# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')])),
            ],
        ),
    ]
