# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180416_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='pet_type',
        ),
    ]
