# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pet_pet_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.Pet'),
        ),
    ]
