# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordinary',
            fields=[
                ('pet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Pet')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.pet',),
        ),
    ]
